name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: Backend
        run: npm install

      # Run backend tests
      # - name: Run backend tests
      #   working-directory: Backend
      #   run: npm test

      # Build Docker image for backend
      - name: Build Docker image for backend
        working-directory: Backend
        run: |
          docker build -t fotoflask-backend .

      # Log in to Docker Hub and push Docker image for backend
      - name: Push Docker image for backend to registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag fotoflask-backend poojyanth/fotoflask-backend
          docker push poojyanth/fotoflask-backend
