name: fotoflask-frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build Docker image
        run: |
          docker build -t fotoflask-frontend .

      - name: Push Docker image to registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag fotoflask-frontend poojyanth/fotoflask-frontend
          docker push poojyanth/fotoflask-frontend
